version: '3.8'

services:
  php:
    container_name: php
    working_dir: /var/www/html
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '8000:8000'
    volumes:
      - ../www:/var/www/html/
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ../db:/var/lib/mysql

volumes:
  www:
  db: